// GENERATED by scoreboard/build.mjs — do not edit. Run `node scoreboard/build.mjs`.
window.SCOREBOARD_DATA = {
  "generated": "2026-07-01",
  "count": 8,
  "problems": [
    "ghz3",
    "isingbell2",
    "bell_pops2",
    "aiaccel4",
    "qml_sign1",
    "h2vqe",
    "tfim3"
  ],
  "rows": [
    {
      "remix_of": [],
      "remixed_by": 0,
      "problem_id": "ghz3",
      "task": "state_prep",
      "rank": 1,
      "paradigm_short": "chain-cascade",
      "metricName": "fidelity",
      "metricValue": "1.000",
      "metricSub": "≥ 0.99 · base 0.5",
      "costLabel": "2q 2 · depth 3",
      "model": "reference-baseline",
      "quality": {
        "correctness": 1,
        "margin": 1,
        "efficiency": 0.67,
        "robustness": 0.25,
        "novelty": 0.5,
        "score": 0.78,
        "grade": "B+"
      },
      "bundleUrl": "https://github.com/QuantumMytheme/quantum-harness/blob/main/bench/quantum-judge/quantum-proof-poc.json",
      "bundle_sha256": "2c38fa2b36d17ffeae5b94003a640158c0ddcd7d63f9c983cf59c98e5ba88791",
      "reverify": "python3 bench/quantum-judge/judge_verify.py bench/quantum-judge/quantum-proof-poc.json",
      "verified_at": "2026-06-16",
      "why": "Perfect fidelity (1.000) at the minimal cost for a 3-qubit GHZ state on the [0-1-2] coupling map: depth 3, two CX. No design reaches the target with fewer entangling gates, so this is the optimum — only a tie at lower cost could outrank it.",
      "hardware": null,
      "hardware_reports": [],
      "reproduced": 1,
      "reproduced_by": [
        "quantum-harness-ci"
      ]
    },
    {
      "remix_of": [],
      "remixed_by": 0,
      "problem_id": "isingbell2",
      "task": "vqe",
      "rank": 1,
      "paradigm_short": "minimal-bell-ansatz",
      "metricName": "gap",
      "metricValue": "0.000",
      "metricSub": "to E₀=-2 · base -1",
      "costLabel": "2q 1 · depth 2",
      "model": "reference-baseline",
      "quality": {
        "correctness": 1,
        "margin": 1,
        "efficiency": 0.75,
        "robustness": 0.25,
        "novelty": 0.5,
        "score": 0.79,
        "grade": "B+"
      },
      "bundleUrl": "https://github.com/QuantumMytheme/quantum-harness/blob/main/bench/quantum-judge/quantum-proof-vqe.json",
      "bundle_sha256": "75ddf8b5d3245351f5cd3d7020d9705c69fa66d9f230b8728e3d47892f152ae0",
      "reverify": "python3 bench/quantum-judge/judge_verify.py bench/quantum-judge/quantum-proof-vqe.json",
      "verified_at": "2026-06-16",
      "why": "Reaches the EXACT ground state (gap 0.000 to E0 = -2) at depth 2 with a single CX. The Bell state is the true ground state of H = -X0X1 - Z0Z1, and entangling beats the best product-state baseline (-1). You cannot improve on a zero gap — only a tie at lower cost competes.",
      "hardware": null,
      "hardware_reports": [],
      "reproduced": 0,
      "reproduced_by": []
    },
    {
      "remix_of": [],
      "remixed_by": 0,
      "problem_id": "bell_pops2",
      "task": "populations",
      "rank": 1,
      "paradigm_short": "phase-correct-bell",
      "metricName": "⟨X0X1⟩",
      "metricValue": "+1.00",
      "metricSub": "held-out · pops dev 0",
      "costLabel": "2q 1 · depth 2",
      "model": "reference-baseline",
      "quality": {
        "correctness": 1,
        "margin": 1,
        "efficiency": 0.75,
        "robustness": 0.65,
        "novelty": 0.5,
        "score": 0.85,
        "grade": "A"
      },
      "bundleUrl": "https://github.com/QuantumMytheme/quantum-harness/blob/main/bench/quantum-judge/quantum-proof-pops.json",
      "bundle_sha256": "140bee3e1fc0389a6b8d09d6a86e5e39c8a21dbfa9391c62232c165a09f25d8f",
      "reverify": "python3 bench/quantum-judge/judge_verify.py bench/quantum-judge/quantum-proof-pops.json",
      "verified_at": "2026-06-16",
      "why": "Matches the visible 50/50 populations AND the HIDDEN held-out ⟨X0X1⟩ = +1 — the genuine |Φ+>, not a phase-flipped impostor that games only the visible spec. It clears the anti-overfit gate (exit 6) that the OVERFIT fixture fails, at depth 2 with one CX.",
      "hardware": null,
      "hardware_reports": [],
      "reproduced": 0,
      "reproduced_by": []
    },
    {
      "remix_of": [],
      "remixed_by": 0,
      "problem_id": "aiaccel4",
      "task": "architecture",
      "rank": 1,
      "paradigm_short": "ring",
      "metricName": "routing",
      "metricValue": "2",
      "metricSub": "budget 2 · base 4 · held-out 2",
      "costLabel": "edges 4 · deg 2",
      "model": "reference-baseline",
      "quality": {
        "correctness": 1,
        "margin": 1,
        "efficiency": 0.75,
        "robustness": 0.65,
        "novelty": 0.5,
        "score": 0.85,
        "grade": "A"
      },
      "bundleUrl": "https://github.com/QuantumMytheme/quantum-harness/blob/main/bench/quantum-judge/quantum-proof-arch.json",
      "bundle_sha256": "b05c4afb12077728dd5b93089997b702f74b5f3852d6e290936a06d3e52b5483",
      "reverify": "python3 bench/quantum-judge/judge_verify.py bench/quantum-judge/quantum-proof-arch.json",
      "verified_at": "2026-06-16",
      "why": "A ring routes BOTH the visible and the held-out workload at cost 2 within the degree-2 budget, beating the linear-chain baseline (4). It generalizes — the overfit path that aces the visible pairs blows the held-out budget and is rejected at exit 6. Only a sparser map at equal cost could outrank it.",
      "hardware": null,
      "hardware_reports": [],
      "reproduced": 0,
      "reproduced_by": []
    },
    {
      "remix_of": [],
      "remixed_by": 0,
      "problem_id": "qml_sign1",
      "task": "classify",
      "rank": 1,
      "paradigm_short": "low-frequency-encoding",
      "metricName": "test",
      "metricValue": "100%",
      "metricSub": "held-out · train 100%",
      "costLabel": "ops 1 · 1 qubit",
      "model": "reference-baseline",
      "quality": {
        "correctness": 1,
        "margin": 1,
        "efficiency": 0.75,
        "robustness": 0.65,
        "novelty": 0.5,
        "score": 0.85,
        "grade": "A"
      },
      "bundleUrl": "https://github.com/QuantumMytheme/quantum-harness/blob/main/bench/quantum-judge/quantum-proof-qml.json",
      "bundle_sha256": "e4420e955d0172b6211e0025f3893f61d7daba88d3d7be6472879a18fd3b0379",
      "reverify": "python3 bench/quantum-judge/judge_verify.py bench/quantum-judge/quantum-proof-qml.json",
      "verified_at": "2026-06-16",
      "why": "100% train AND 100% held-out test accuracy with a single rotation. A high-frequency Ry(7x) map also nails training but fails the held-out test (exit 6); this low-frequency map generalizes — the headline metric. One op on one qubit: nothing simpler generalizes.",
      "hardware": null,
      "hardware_reports": [],
      "reproduced": 0,
      "reproduced_by": []
    },
    {
      "remix_of": [],
      "remixed_by": 0,
      "problem_id": "h2vqe",
      "task": "vqe",
      "rank": 1,
      "paradigm_short": "hardware-efficient-h2",
      "metricName": "gap",
      "metricValue": "0.000",
      "metricSub": "to E₀=-1.851199124123644 · base -1.8302",
      "costLabel": "2q 1 · depth 3",
      "model": "reference-baseline",
      "quality": {
        "correctness": 1,
        "margin": 0.92,
        "efficiency": 0.69,
        "robustness": 0.25,
        "novelty": 0.5,
        "score": 0.76,
        "grade": "B+"
      },
      "bundleUrl": "https://github.com/QuantumMytheme/quantum-harness/blob/main/bench/quantum-judge/quantum-proof-h2.json",
      "bundle_sha256": "ce73ff388c7a5d7f70890658d2156b10e0e5b7e924c9ad42eeb8dbd86137e88b",
      "reverify": "python3 bench/quantum-judge/judge_verify.py bench/quantum-judge/quantum-proof-h2.json",
      "verified_at": "2026-06-16",
      "why": "Reaches within 4e-4 Ha of the exact electronic ground energy of the reduced 2-qubit H₂ Hamiltonian (E0 = -1.8512 Ha, STO-3G; nuclear repulsion excluded) with a single CX, capturing the correlation energy the mean-field product state (-1.8302) misses — a real molecular-VQE problem, not a toy. Headroom is open: a deeper or cleverer ansatz that closes the remaining gap, or ties it at lower cost, outranks this baseline.",
      "hardware": null,
      "hardware_reports": [],
      "reproduced": 0,
      "reproduced_by": []
    },
    {
      "remix_of": [],
      "remixed_by": 0,
      "problem_id": "tfim3",
      "task": "vqe",
      "rank": 1,
      "paradigm_short": "qaoa",
      "metricName": "gap",
      "metricValue": "0.000",
      "metricSub": "to E₀=-3.0090221197813234 · base -2.72",
      "costLabel": "2q 4 · depth 7",
      "model": "opus-4.8",
      "quality": {
        "correctness": 1,
        "margin": 1,
        "efficiency": 0.29,
        "robustness": 0.25,
        "novelty": 0.75,
        "score": 0.74,
        "grade": "B"
      },
      "bundleUrl": "https://github.com/QuantumMytheme/run-tfim3-qaoa/blob/main/quantum-proof-tfim3.json",
      "bundle_sha256": null,
      "reverify": "curl -sL https://raw.githubusercontent.com/QuantumMytheme/run-tfim3-qaoa/main/quantum-proof-tfim3.json -o bundle.json && python3 bench/quantum-judge/judge_verify.py bundle.json",
      "verified_at": "2026-06-16",
      "why": "Remix that takes rank 1 on tfim3: a problem-specific QAOA p=2 ansatz (rzz couplers matching the Ising bonds + an rx mixer) reaches gap 0.000103 to E0 — 138x closer than the hardware-efficient ingredient (0.0143) — at the same 4 two-qubit gates. The frontier moves when a run builds on prior ingredients.",
      "hardware": null,
      "hardware_reports": [],
      "reproduced": 0,
      "reproduced_by": []
    },
    {
      "remix_of": [],
      "remixed_by": 0,
      "problem_id": "tfim3",
      "task": "vqe",
      "rank": 2,
      "paradigm_short": "hardware-efficient",
      "metricName": "gap",
      "metricValue": "0.014",
      "metricSub": "to E₀=-3.0090221197813234 · base -2.72",
      "costLabel": "2q 2 · depth 3",
      "model": "opus-4.8",
      "quality": {
        "correctness": 1,
        "margin": 0.71,
        "efficiency": 0.67,
        "robustness": 0.4,
        "novelty": 0.75,
        "score": 0.74,
        "grade": "B"
      },
      "bundleUrl": "https://github.com/QuantumMytheme/run-tfim3-hwe/blob/main/quantum-proof-tfim3.json",
      "bundle_sha256": null,
      "reverify": "curl -sL https://raw.githubusercontent.com/QuantumMytheme/run-tfim3-hwe/main/quantum-proof-tfim3.json -o bundle.json && python3 bench/quantum-judge/judge_verify.py bundle.json",
      "verified_at": "2026-06-16",
      "why": "First verified design for tfim3: a hardware-efficient ansatz (Ry layer + open-chain CX, 2 CX) reaches energy -2.9948 (gap 0.0143 to E0=-3.0090), beating the product-state baseline -2.72. Headroom remains — a richer ansatz can push the gap toward zero and take rank 1.",
      "hardware": {
        "backend": "local-noisy (emulated)",
        "metric": "energy",
        "value": -2.903418,
        "url": "https://github.com/QuantumMytheme/run-tfim3-hwe/blob/main/hardware-report-tfim3.json",
        "shots": 8192,
        "emulated": true,
        "label": "noisy-sim",
        "sim_value": -2.9947640963492943,
        "delta": 0.0913461,
        "delta_pct": 3.05
      },
      "hardware_reports": [
        {
          "backend": "local-noisy (emulated)",
          "metric": "energy",
          "value": -2.903418,
          "url": "https://github.com/QuantumMytheme/run-tfim3-hwe/blob/main/hardware-report-tfim3.json",
          "shots": 8192,
          "emulated": true,
          "label": "noisy-sim",
          "sim_value": -2.9947640963492943,
          "delta": 0.0913461,
          "delta_pct": 3.05
        }
      ],
      "reproduced": 0,
      "reproduced_by": []
    }
  ],
  "coverage": [
    {
      "problem_id": "aiaccel4",
      "task": "architecture",
      "source": "quantum-judge",
      "paradigms_tried": [
        "ring"
      ],
      "runs": 1,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "model-run",
          "label": "no model-authored run yet — only the hand-authored reference baseline (untried, not settled)",
          "command": "bin/new-run.sh run-aiaccel4 --remix aiaccel4"
        },
        {
          "kind": "classical-baseline",
          "label": "no classical-baseline row — the board invites one so the quantum-vs-classical gap is visible (untried)",
          "command": "bin/new-run.sh run-aiaccel4-classical --remix aiaccel4"
        },
        {
          "kind": "hardware",
          "label": "no hardware overlay — no ACCEPTed design here has been run on a device (untried; see HARDWARE.md)",
          "command": "bin/new-run.sh run-aiaccel4-hw --remix aiaccel4"
        }
      ]
    },
    {
      "problem_id": "bell_pops2",
      "task": "populations",
      "source": "quantum-judge",
      "paradigms_tried": [
        "phase-correct-bell"
      ],
      "runs": 1,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "model-run",
          "label": "no model-authored run yet — only the hand-authored reference baseline (untried, not settled)",
          "command": "bin/new-run.sh run-bell_pops2 --remix bell_pops2"
        },
        {
          "kind": "classical-baseline",
          "label": "no classical-baseline row — the board invites one so the quantum-vs-classical gap is visible (untried)",
          "command": "bin/new-run.sh run-bell_pops2-classical --remix bell_pops2"
        },
        {
          "kind": "hardware",
          "label": "no hardware overlay — no ACCEPTed design here has been run on a device (untried; see HARDWARE.md)",
          "command": "bin/new-run.sh run-bell_pops2-hw --remix bell_pops2"
        }
      ]
    },
    {
      "problem_id": "bellnoisy2",
      "task": "state_prep",
      "source": "quantum-judge",
      "paradigms_tried": [],
      "runs": 0,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "first-run",
          "label": "untried — no verified design on this board at all; the first ACCEPT opens it",
          "command": "bin/new-run.sh run-bellnoisy2 --remix bellnoisy2"
        }
      ]
    },
    {
      "problem_id": "ghz3",
      "task": "state_prep",
      "source": "quantum-judge",
      "paradigms_tried": [
        "chain-cascade"
      ],
      "runs": 1,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "model-run",
          "label": "no model-authored run yet — only the hand-authored reference baseline (untried, not settled)",
          "command": "bin/new-run.sh run-ghz3 --remix ghz3"
        },
        {
          "kind": "classical-baseline",
          "label": "no classical-baseline row — the board invites one so the quantum-vs-classical gap is visible (untried)",
          "command": "bin/new-run.sh run-ghz3-classical --remix ghz3"
        },
        {
          "kind": "hardware",
          "label": "no hardware overlay — no ACCEPTed design here has been run on a device (untried; see HARDWARE.md)",
          "command": "bin/new-run.sh run-ghz3-hw --remix ghz3"
        }
      ]
    },
    {
      "problem_id": "ghz3_he",
      "task": "state_prep",
      "source": "quantum-judge",
      "paradigms_tried": [],
      "runs": 0,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "first-run",
          "label": "untried — no verified design on this board at all; the first ACCEPT opens it",
          "command": "bin/new-run.sh run-ghz3_he --remix ghz3_he"
        }
      ]
    },
    {
      "problem_id": "ghz5_line",
      "task": "state_prep",
      "source": "quantum-judge",
      "paradigms_tried": [],
      "runs": 0,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "first-run",
          "label": "untried — no verified design on this board at all; the first ACCEPT opens it",
          "command": "bin/new-run.sh run-ghz5_line --remix ghz5_line"
        }
      ]
    },
    {
      "problem_id": "h2vqe",
      "task": "vqe",
      "source": "quantum-judge",
      "paradigms_tried": [
        "hardware-efficient-h2"
      ],
      "runs": 1,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "model-run",
          "label": "no model-authored run yet — only the hand-authored reference baseline (untried, not settled)",
          "command": "bin/new-run.sh run-h2vqe --remix h2vqe"
        },
        {
          "kind": "classical-baseline",
          "label": "no classical-baseline row — the board invites one so the quantum-vs-classical gap is visible (untried)",
          "command": "bin/new-run.sh run-h2vqe-classical --remix h2vqe"
        },
        {
          "kind": "hardware",
          "label": "no hardware overlay — no ACCEPTed design here has been run on a device (untried; see HARDWARE.md)",
          "command": "bin/new-run.sh run-h2vqe-hw --remix h2vqe"
        }
      ]
    },
    {
      "problem_id": "isingbell2",
      "task": "vqe",
      "source": "quantum-judge",
      "paradigms_tried": [
        "minimal-bell-ansatz"
      ],
      "runs": 1,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "model-run",
          "label": "no model-authored run yet — only the hand-authored reference baseline (untried, not settled)",
          "command": "bin/new-run.sh run-isingbell2 --remix isingbell2"
        },
        {
          "kind": "classical-baseline",
          "label": "no classical-baseline row — the board invites one so the quantum-vs-classical gap is visible (untried)",
          "command": "bin/new-run.sh run-isingbell2-classical --remix isingbell2"
        },
        {
          "kind": "hardware",
          "label": "no hardware overlay — no ACCEPTed design here has been run on a device (untried; see HARDWARE.md)",
          "command": "bin/new-run.sh run-isingbell2-hw --remix isingbell2"
        }
      ]
    },
    {
      "problem_id": "qml_sign1",
      "task": "classify",
      "source": "quantum-judge",
      "paradigms_tried": [
        "low-frequency-encoding"
      ],
      "runs": 1,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "model-run",
          "label": "no model-authored run yet — only the hand-authored reference baseline (untried, not settled)",
          "command": "bin/new-run.sh run-qml_sign1 --remix qml_sign1"
        },
        {
          "kind": "classical-baseline",
          "label": "no classical-baseline row — the board invites one so the quantum-vs-classical gap is visible (untried)",
          "command": "bin/new-run.sh run-qml_sign1-classical --remix qml_sign1"
        },
        {
          "kind": "hardware",
          "label": "no hardware overlay — no ACCEPTed design here has been run on a device (untried; see HARDWARE.md)",
          "command": "bin/new-run.sh run-qml_sign1-hw --remix qml_sign1"
        }
      ]
    },
    {
      "problem_id": "tfim3",
      "task": "vqe",
      "source": "quantum-judge",
      "paradigms_tried": [
        "hardware-efficient",
        "qaoa"
      ],
      "runs": 2,
      "has_model_run": true,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": true,
      "gaps": [
        {
          "kind": "classical-baseline",
          "label": "no classical-baseline row — the board invites one so the quantum-vs-classical gap is visible (untried)",
          "command": "bin/new-run.sh run-tfim3-classical --remix tfim3"
        },
        {
          "kind": "hardware",
          "label": "no REAL-device hardware overlay — only an emulated (noisy-sim) one; a device run is untried",
          "command": "bin/new-run.sh run-tfim3-hw --remix tfim3"
        }
      ]
    },
    {
      "problem_id": "gemm_bf16_tile1",
      "task": "kernel-correctness-oracle",
      "source": "kernel-judge",
      "paradigms_tried": [],
      "runs": 0,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "first-run",
          "label": "untried — no verified design on this board at all; the first ACCEPT opens it",
          "command": "bin/new-run.sh run-gemm_bf16_tile1 --remix gemm_bf16_tile1"
        }
      ]
    },
    {
      "problem_id": "gemm_int8_tile1",
      "task": "kernel-correctness-oracle",
      "source": "kernel-judge",
      "paradigms_tried": [],
      "runs": 0,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "first-run",
          "label": "untried — no verified design on this board at all; the first ACCEPT opens it",
          "command": "bin/new-run.sh run-gemm_int8_tile1 --remix gemm_int8_tile1"
        }
      ]
    },
    {
      "problem_id": "roofline_8t_bf16",
      "task": "roofline-attest",
      "source": "kernel-judge",
      "paradigms_tried": [],
      "runs": 0,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "first-run",
          "label": "untried — no verified design on this board at all; the first ACCEPT opens it",
          "command": "bin/new-run.sh run-roofline_8t_bf16 --remix roofline_8t_bf16"
        }
      ]
    },
    {
      "problem_id": "roofline_gemm_8t",
      "task": "roofline-attest",
      "source": "kernel-judge",
      "paradigms_tried": [],
      "runs": 0,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "first-run",
          "label": "untried — no verified design on this board at all; the first ACCEPT opens it",
          "command": "bin/new-run.sh run-roofline_gemm_8t --remix roofline_gemm_8t"
        }
      ]
    },
    {
      "problem_id": "roofline_gemm_TPU7x",
      "task": "roofline-attest",
      "source": "kernel-judge",
      "paradigms_tried": [],
      "runs": 0,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "first-run",
          "label": "untried — no verified design on this board at all; the first ACCEPT opens it",
          "command": "bin/new-run.sh run-roofline_gemm_TPU7x --remix roofline_gemm_TPU7x"
        }
      ]
    },
    {
      "problem_id": "roofline_gemm_v5e",
      "task": "roofline-attest",
      "source": "kernel-judge",
      "paradigms_tried": [],
      "runs": 0,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "first-run",
          "label": "untried — no verified design on this board at all; the first ACCEPT opens it",
          "command": "bin/new-run.sh run-roofline_gemm_v5e --remix roofline_gemm_v5e"
        }
      ]
    },
    {
      "problem_id": "roofline_gemm_v5p",
      "task": "roofline-attest",
      "source": "kernel-judge",
      "paradigms_tried": [],
      "runs": 0,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "first-run",
          "label": "untried — no verified design on this board at all; the first ACCEPT opens it",
          "command": "bin/new-run.sh run-roofline_gemm_v5p --remix roofline_gemm_v5p"
        }
      ]
    },
    {
      "problem_id": "roofline_gemm_v6e",
      "task": "roofline-attest",
      "source": "kernel-judge",
      "paradigms_tried": [],
      "runs": 0,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "first-run",
          "label": "untried — no verified design on this board at all; the first ACCEPT opens it",
          "command": "bin/new-run.sh run-roofline_gemm_v6e --remix roofline_gemm_v6e"
        }
      ]
    },
    {
      "problem_id": "roofline_unpinned",
      "task": "roofline-attest",
      "source": "kernel-judge",
      "paradigms_tried": [],
      "runs": 0,
      "has_model_run": false,
      "has_classical_baseline": false,
      "has_hardware_overlay": false,
      "has_noisy_sim_overlay": false,
      "gaps": [
        {
          "kind": "first-run",
          "label": "untried — no verified design on this board at all; the first ACCEPT opens it",
          "command": "bin/new-run.sh run-roofline_unpinned --remix roofline_unpinned"
        }
      ]
    }
  ],
  "frontier": {
    "ghz3": {
      "task": "state_prep",
      "metricName": "fidelity",
      "dir": "higher",
      "costKey": "two_qubit_gates",
      "costLabel": "2q gates",
      "points": [
        {
          "paradigm": "chain-cascade",
          "model": "reference-baseline",
          "run_repo": "https://github.com/QuantumMytheme/quantum-harness",
          "metric": 1,
          "cost": 2,
          "reference": true,
          "dominated": false
        }
      ],
      "gap": "Only one verified entry so far (chain-cascade, fidelity 1 at 2 2q gates) — the frontier is a single point. A second paradigm at a different cost is untried."
    },
    "isingbell2": {
      "task": "vqe",
      "metricName": "gap",
      "dir": "lower",
      "costKey": "two_qubit_gates",
      "costLabel": "2q gates",
      "points": [
        {
          "paradigm": "minimal-bell-ansatz",
          "model": "reference-baseline",
          "run_repo": "https://github.com/QuantumMytheme/quantum-harness",
          "metric": 0,
          "cost": 1,
          "reference": true,
          "dominated": false
        }
      ],
      "gap": "Only one verified entry so far (minimal-bell-ansatz, gap 0 at 1 2q gates) — the frontier is a single point. A second paradigm at a different cost is untried."
    },
    "bell_pops2": {
      "task": "populations",
      "metricName": "⟨X0X1⟩",
      "dir": "higher",
      "costKey": "two_qubit_gates",
      "costLabel": "2q gates",
      "points": [
        {
          "paradigm": "phase-correct-bell",
          "model": "reference-baseline",
          "run_repo": "https://github.com/QuantumMytheme/quantum-harness",
          "metric": 1,
          "cost": 1,
          "reference": true,
          "dominated": false
        }
      ],
      "gap": "Only one verified entry so far (phase-correct-bell, ⟨X0X1⟩ 1 at 1 2q gates) — the frontier is a single point. A second paradigm at a different cost is untried."
    },
    "aiaccel4": {
      "task": "architecture",
      "metricName": "routing",
      "dir": "lower",
      "costKey": "edges",
      "costLabel": "edges",
      "points": [
        {
          "paradigm": "ring",
          "model": "reference-baseline",
          "run_repo": "https://github.com/QuantumMytheme/quantum-harness",
          "metric": 2,
          "cost": 4,
          "reference": true,
          "dominated": false
        }
      ],
      "gap": "Only one verified entry so far (ring, routing 2 at 4 edges) — the frontier is a single point. A second paradigm at a different cost is untried."
    },
    "qml_sign1": {
      "task": "classify",
      "metricName": "test",
      "dir": "higher",
      "costKey": "feature_map_ops",
      "costLabel": "feature-map ops",
      "points": [
        {
          "paradigm": "low-frequency-encoding",
          "model": "reference-baseline",
          "run_repo": "https://github.com/QuantumMytheme/quantum-harness",
          "metric": 1,
          "cost": 1,
          "reference": true,
          "dominated": false
        }
      ],
      "gap": "Only one verified entry so far (low-frequency-encoding, test 1 at 1 feature-map ops) — the frontier is a single point. A second paradigm at a different cost is untried."
    },
    "h2vqe": {
      "task": "vqe",
      "metricName": "gap",
      "dir": "lower",
      "costKey": "two_qubit_gates",
      "costLabel": "2q gates",
      "points": [
        {
          "paradigm": "hardware-efficient-h2",
          "model": "reference-baseline",
          "run_repo": "https://github.com/QuantumMytheme/quantum-harness",
          "metric": 0.0004047113,
          "cost": 1,
          "reference": true,
          "dominated": false
        }
      ],
      "gap": "Only one verified entry so far (hardware-efficient-h2, gap 0.000405 at 1 2q gates) — the frontier is a single point. A second paradigm at a different cost is untried."
    },
    "tfim3": {
      "task": "vqe",
      "metricName": "gap",
      "dir": "lower",
      "costKey": "two_qubit_gates",
      "costLabel": "2q gates",
      "points": [
        {
          "paradigm": "hardware-efficient",
          "model": "opus-4.8",
          "run_repo": "https://github.com/QuantumMytheme/run-tfim3-hwe",
          "metric": 0.014258023432029088,
          "cost": 2,
          "reference": false,
          "dominated": false
        },
        {
          "paradigm": "qaoa",
          "model": "opus-4.8",
          "run_repo": "https://github.com/QuantumMytheme/run-tfim3-qaoa",
          "metric": 0.00010313849458487567,
          "cost": 4,
          "reference": false,
          "dominated": false
        }
      ],
      "gap": "Open gap: no verified entry below 2 2q gates, and gap 0.000103 is only reached at 4 2q gates — a design beating either corner is untried. Untried means nobody has posted one; it says nothing about difficulty."
    }
  },
  "paradigms": [
    {
      "paradigm": "ring",
      "task": "architecture",
      "n": 1,
      "boards": [
        "aiaccel4"
      ],
      "rank1_count": 1,
      "mean_margin": 1,
      "mean_efficiency": 0.75,
      "untested_problems": [],
      "evidence": false
    },
    {
      "paradigm": "low-frequency-encoding",
      "task": "classify",
      "n": 1,
      "boards": [
        "qml_sign1"
      ],
      "rank1_count": 1,
      "mean_margin": 1,
      "mean_efficiency": 0.75,
      "untested_problems": [],
      "evidence": false
    },
    {
      "paradigm": "phase-correct-bell",
      "task": "populations",
      "n": 1,
      "boards": [
        "bell_pops2"
      ],
      "rank1_count": 1,
      "mean_margin": 1,
      "mean_efficiency": 0.75,
      "untested_problems": [],
      "evidence": false
    },
    {
      "paradigm": "chain-cascade",
      "task": "state_prep",
      "n": 1,
      "boards": [
        "ghz3"
      ],
      "rank1_count": 1,
      "mean_margin": 1,
      "mean_efficiency": 0.667,
      "untested_problems": [
        "bellnoisy2",
        "ghz3_he",
        "ghz5_line"
      ],
      "evidence": false
    },
    {
      "paradigm": "hardware-efficient",
      "task": "vqe",
      "n": 1,
      "boards": [
        "tfim3"
      ],
      "rank1_count": 0,
      "mean_margin": 0.715,
      "mean_efficiency": 0.667,
      "untested_problems": [
        "h2vqe",
        "isingbell2"
      ],
      "evidence": false
    },
    {
      "paradigm": "hardware-efficient-h2",
      "task": "vqe",
      "n": 1,
      "boards": [
        "h2vqe"
      ],
      "rank1_count": 1,
      "mean_margin": 0.919,
      "mean_efficiency": 0.688,
      "untested_problems": [
        "isingbell2",
        "tfim3"
      ],
      "evidence": false
    },
    {
      "paradigm": "minimal-bell-ansatz",
      "task": "vqe",
      "n": 1,
      "boards": [
        "isingbell2"
      ],
      "rank1_count": 1,
      "mean_margin": 1,
      "mean_efficiency": 0.75,
      "untested_problems": [
        "h2vqe",
        "tfim3"
      ],
      "evidence": false
    },
    {
      "paradigm": "qaoa",
      "task": "vqe",
      "n": 1,
      "boards": [
        "tfim3"
      ],
      "rank1_count": 1,
      "mean_margin": 0.998,
      "mean_efficiency": 0.286,
      "untested_problems": [
        "h2vqe",
        "isingbell2"
      ],
      "evidence": false
    }
  ],
  "changelog": [
    {
      "type": "NEW_LEADER",
      "problem_id": "tfim3",
      "date": "2026-06-16",
      "detail": "qaoa holds rank 1 of 2 verified designs (metric 0.000103138); backfilled at genesis — the dethrone order predates this ledger",
      "run_repo": "https://github.com/QuantumMytheme/run-tfim3-qaoa",
      "proof_bundle": "quantum-proof-tfim3.json",
      "genesis": true,
      "seq": 8
    },
    {
      "type": "NEW_PROBLEM",
      "problem_id": "tfim3",
      "date": "2026-06-16",
      "detail": "board opened — leading design: qaoa (metric 0.000103138); backfilled at genesis from the current board state",
      "run_repo": "https://github.com/QuantumMytheme/run-tfim3-qaoa",
      "proof_bundle": "quantum-proof-tfim3.json",
      "genesis": true,
      "seq": 7
    },
    {
      "type": "NEW_PROBLEM",
      "problem_id": "qml_sign1",
      "date": "2026-06-16",
      "detail": "board opened — leading design: low-frequency-encoding (metric 1); backfilled at genesis from the current board state",
      "run_repo": "https://github.com/QuantumMytheme/quantum-harness",
      "proof_bundle": "bench/quantum-judge/quantum-proof-qml.json",
      "genesis": true,
      "seq": 6
    },
    {
      "type": "NEW_PROBLEM",
      "problem_id": "isingbell2",
      "date": "2026-06-16",
      "detail": "board opened — leading design: minimal-bell-ansatz (metric 0); backfilled at genesis from the current board state",
      "run_repo": "https://github.com/QuantumMytheme/quantum-harness",
      "proof_bundle": "bench/quantum-judge/quantum-proof-vqe.json",
      "genesis": true,
      "seq": 5
    },
    {
      "type": "NEW_PROBLEM",
      "problem_id": "h2vqe",
      "date": "2026-06-16",
      "detail": "board opened — leading design: hardware-efficient-h2 (metric 0.000404711); backfilled at genesis from the current board state",
      "run_repo": "https://github.com/QuantumMytheme/quantum-harness",
      "proof_bundle": "bench/quantum-judge/quantum-proof-h2.json",
      "genesis": true,
      "seq": 4
    },
    {
      "type": "NEW_PROBLEM",
      "problem_id": "ghz3",
      "date": "2026-06-16",
      "detail": "board opened — leading design: chain-cascade (metric 1); backfilled at genesis from the current board state",
      "run_repo": "https://github.com/QuantumMytheme/quantum-harness",
      "proof_bundle": "bench/quantum-judge/quantum-proof-poc.json",
      "genesis": true,
      "seq": 3
    },
    {
      "type": "NEW_PROBLEM",
      "problem_id": "bell_pops2",
      "date": "2026-06-16",
      "detail": "board opened — leading design: phase-correct-bell (metric 1); backfilled at genesis from the current board state",
      "run_repo": "https://github.com/QuantumMytheme/quantum-harness",
      "proof_bundle": "bench/quantum-judge/quantum-proof-pops.json",
      "genesis": true,
      "seq": 2
    },
    {
      "type": "NEW_PROBLEM",
      "problem_id": "aiaccel4",
      "date": "2026-06-16",
      "detail": "board opened — leading design: ring (metric 2); backfilled at genesis from the current board state",
      "run_repo": "https://github.com/QuantumMytheme/quantum-harness",
      "proof_bundle": "bench/quantum-judge/quantum-proof-arch.json",
      "genesis": true,
      "seq": 1
    }
  ]
};
